export const retailers = [
 {id:'shoprite',name:'Shoprite',colour:'#e31e24',website:'https://www.shoprite.co.za',dataSource:'mock'},
 {id:'checkers',name:'Checkers',colour:'#e31e24',website:'https://www.checkers.co.za',dataSource:'mock'},
 {id:'picknpay',name:'Pick n Pay',colour:'#e61e2a',website:'https://www.pnp.co.za',dataSource:'mock'},
 {id:'woolworths',name:'Woolworths',colour:'#232323',website:'https://www.woolworths.co.za',dataSource:'mock'},
 {id:'spar',name:'SPAR',colour:'#db1d2f',website:'https://www.spar.co.za',dataSource:'unavailable'}
];
export const locations = [{name:'Cape Town',lat:-33.9249,lng:18.4241},{name:'Johannesburg',lat:-26.2041,lng:28.0473},{name:'Pretoria',lat:-25.7479,lng:28.2293},{name:'Durban',lat:-29.8587,lng:31.0218}];
export const products = [
 {id:'huletts-brown-sugar-2kg',barcode:'6001019000012',brand:'Huletts',name:'Brown Sugar',variant:'',quantity:2,unit:'kg',category:'Pantry',image:'🟤',aliases:['huletts brown sugar','brown sugar'], prices:[['shoprite','Shoprite Sea Point','Main Rd, Sea Point, Cape Town',49.99,3.2,'in_stock',18],['checkers','Checkers V&A Waterfront','Breakwater Blvd, Cape Town',52.99,4.1,'in_stock',42],['picknpay','Pick n Pay Green Point','Main Rd, Green Point, Cape Town',54.99,2.8,'in_stock',120],['woolworths','Woolworths Gardens','Kloof St, Gardens, Cape Town',59.99,5.4,'in_stock',2880]]},
 {id:'tastic-rice-5kg',barcode:'6001234000027',brand:'Tastic',name:'Parboiled Rice',variant:'',quantity:5,unit:'kg',category:'Pantry',image:'🍚',aliases:['tastic rice','rice'],prices:[['shoprite','Shoprite Sea Point','Main Rd, Sea Point, Cape Town',109.99,3.2,'in_stock',25],['checkers','Checkers V&A Waterfront','Breakwater Blvd, Cape Town',114.99,4.1,'in_stock',60],['picknpay','Pick n Pay Green Point','Main Rd, Green Point, Cape Town',119.99,2.8,'in_stock',25]]},
 {id:'coca-cola-2l',barcode:'5449000000996',brand:'Coca-Cola',name:'Original Taste',variant:'',quantity:2,unit:'L',category:'Beverages',image:'🥤',aliases:['coca cola','coke'],prices:[['shoprite','Shoprite Sea Point','Main Rd, Sea Point, Cape Town',21.99,3.2,'in_stock',12],['checkers','Checkers V&A Waterfront','Breakwater Blvd, Cape Town',24.99,4.1,'in_stock',33],['picknpay','Pick n Pay Green Point','Main Rd, Green Point, Cape Town',22.99,2.8,'in_stock',10],['woolworths','Woolworths Gardens','Kloof St, Gardens, Cape Town',28.99,5.4,'in_stock',90]]},
 {id:'omo-3kg',barcode:'6001087000035',brand:'OMO',name:'Auto Washing Powder',variant:'',quantity:3,unit:'kg',category:'Household',image:'🫧',aliases:['omo washing powder','omo'],prices:[['shoprite','Shoprite Sea Point','Main Rd, Sea Point, Cape Town',119.99,3.2,'in_stock',55],['checkers','Checkers V&A Waterfront','Breakwater Blvd, Cape Town',124.99,4.1,'in_stock',90],['picknpay','Pick n Pay Green Point','Main Rd, Green Point, Cape Town',115.99,2.8,'in_stock',18]]},
 {id:'sunlight-dishwashing-liquid-750ml',barcode:'6001087000042',brand:'Sunlight',name:'Dishwashing Liquid',variant:'',quantity:750,unit:'ml',category:'Household',image:'🧴',aliases:['sunlight dishwashing','sunlight liquid'],prices:[['shoprite','Shoprite Sea Point','Main Rd, Sea Point, Cape Town',34.99,3.2,'in_stock',45],['checkers','Checkers V&A Waterfront','Breakwater Blvd, Cape Town',36.99,4.1,'in_stock',61],['picknpay','Pick n Pay Green Point','Main Rd, Green Point, Cape Town',33.99,2.8,'in_stock',15]]}
];
